CREATE TABLE public.langs(
    id bigserial NOT NULL PRIMARY KEY,
    createdAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER set_timestamp
BEFORE UPDATE ON langs
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();
